export const spellsCombinations: Map<string[], string> = new Map([
    [['quas', 'quas', 'quas'], 'cold_snap'],
    [['quas', 'quas', 'wex'], 'ghost_walk'],
    [['quas', 'wex', 'quas'], 'ghost_walk'],
    [['wex', 'quas', 'quas'], 'ghost_walk'],
    [['quas', 'quas', 'exort'], 'ice_wall'],
    [['quas', 'exort', 'quas'], 'ice_wall'],
    [['exort', 'quas', 'quas'], 'ice_wall'],
    [['wex', 'wex', 'wex'], 'EMP'],
    [['wex', 'wex', 'quas'], 'tornado'],
    [['wex', 'quas', 'wex'], 'tornado'],
    [['quas', 'wex', 'wex'], 'tornado'],
    [['wex', 'wex', 'exort'], 'alacrity'],
    [['wex', 'exort', 'wex'], 'alacrity'],
    [['exort', 'wex', 'wex'], 'alacrity'],
    [['exort', 'exort', 'exort'], 'sun_strike'],
    [['exort', 'exort', 'quas'], 'forge_spirit'],
    [['exort', 'quas', 'exort'], 'forge_spirit'],
    [['quas', 'exort', 'exort'], 'forge_spirit'],
    [['exort', 'exort', 'wex'], 'chaos_meteor'],
    [['exort', 'wex', 'exort'], 'chaos_meteor'],
    [['wex', 'exort', 'exort'], 'chaos_meteor'],
    [['quas', 'exort', 'wex'], 'deafening_blast'],
    [['quas', 'wex', 'exort'], 'deafening_blast'],
    [['exort', 'wex', 'quas'], 'deafening_blast'],
    [['exort', 'quas', 'wex'], 'deafening_blast'],
    [['wex', 'exort', 'quas'], 'deafening_blast'],
    [['wex', 'quas', 'exort'], 'deafening_blast'],
]
)